# Required metadata
sonar.projectKey=Axis_OS_Local
sonar.projectName=Axis_OS_Local
sonar.projectVersion=1.0.0

# Path to the source directories
sonar.sources=/usr/src
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

# Exclusions
sonar.exclusions=sonarqube-26.4.0.121862/**, dist/**, build/**, .git/**, **/assets/sounds/**
