name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        # Точний і перевірений SHA-хеш для офіційного релізу v5.0.0
        uses: SonarSource/sonarqube-scan-action@5d65f577f88421b920bf04f7bdf75f4d852cb7ec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=helgaslop
            -Dsonar.python.version=3.12
